### ISSUE TITLE
template-scenes template is broken

### ISSUE THREAD

**Issue by lay295** [GMU-CS325/cs325-game-prototypes-phaser#16]
Just a small thing, but it looks like it's broken.
https://gmu-cs325.github.io/cs325-game-prototypes/template-scenes/

On Firefox and Chrome it gives me a 404 error because it tried to find button.js when the file is actually named Button.js

Changing it to the correct upper case capitalization on [this line](https://github.com/GMU-CS325/cs325-game-prototypes/blob/a5b7e109ce4e74195a7f665b6e4db681fe681bbc/template-scenes/js/MainMenu.js#L1) fixed it for me.

**Comment by yig** [comment]
Fixed, thank you.
